# this is for the local develoment default profile
spring:
  application:
    name: Enterprice level todo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  # Redis connection config
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      # username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL}
      timeout: 60000
      connect-timeout: 6000
  cache:
    type: redis

    # Database connection settings
  datasource:
      url: ${DATABASE_URL}
      username: ${DATABASE_USER}
      password: ${DATABASE_PWD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5

      # JPA configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # liquibase migration stuff
  liquibase:
    enabled: ${MIGRATE_UP}
    change-log: classpath:db/changelog/db.changelog-master.yaml
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}  # should be 10-15 minutes
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}  # should be 1-30 days 
  issuer: todo-app
google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_SECRET}
  redirect-uri: ${REDIRECT_URI}

# Rate limit config
ratelimit:
  api-limit: ${API_REQUEST_LIMIT}
  api-window-time: ${API_REQUEST_WINDOW_TIME}
  api-wait-time: ${API_REQUEST_WAIT_TIME}


# actuator to the health details and other things
management:
  endpoints:
    web:
      exposure:
        include: "*"
        # in dev only dont show real vals in prod
  endpoint:
    env:
      show-values: ALWAYS
        # include: "*"  

 # Logging level config
# logging:
#   level:
#     org:
#       springframework: DEBUG
#     com:
#       lakshman: DEBUG

  elasticsearch:
    uris: ${ELASTIC_URL}
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PWD}

  # later we will replace these values with the environment variable names