-- liquibase formatted sql

-- changeset lakshman:1771450463197-1
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "createdAt" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "createdBy" BIGINT, 
    "isActive" BOOLEAN NOT NULL, 
    "isDeleted" BOOLEAN NOT NULL,
    "updatedAt" TIMESTAMP(6) WITHOUT TIME ZONE,
    "updatedBy" BIGINT,
    description VARCHAR(255),
    name VARCHAR(255) NOT NULL, 
    CONSTRAINT "rolesPK" PRIMARY KEY (id)
);
-- rollback DROP TABLE roles;


-- changeset lakshman:1771450463197-2
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL, 
    role_id BIGINT NOT NULL, 
    CONSTRAINT "user_rolesPK" PRIMARY KEY (user_id, role_id)
);
-- rollback DROP TABLE user_roles;


-- changeset lakshman:1771450463197-3
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "createdAt" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "createdBy" BIGINT,
    "isActive" BOOLEAN NOT NULL,
    "isDeleted" BOOLEAN NOT NULL,
    "updatedAt" TIMESTAMP(6) WITHOUT TIME ZONE,
    "updatedBy" BIGINT,
    email VARCHAR(255) NOT NULL, 
    "firstName" VARCHAR(255), 
    "lastName" VARCHAR(255), 
    password VARCHAR(255), 
    "providerType" VARCHAR(255),
    provider_id VARCHAR(255), 
    status VARCHAR(255), 
    CONSTRAINT "usersPK" PRIMARY KEY (id)
);
-- rollback DROP TABLE users;


-- changeset lakshman:1771450463197-4
ALTER TABLE roles 
ADD CONSTRAINT UC_ROLESNAME_COL UNIQUE (name);
-- rollback ALTER TABLE roles DROP CONSTRAINT UC_ROLESNAME_COL;

-- changeset lakshman:1771450463197-5
ALTER TABLE users 
ADD CONSTRAINT UC_USERSEMAIL_COL UNIQUE (email);
-- rollback ALTER TABLE users DROP CONSTRAINT UC_USERSEMAIL_COL;

-- changeset lakshman:1771450463197-6
ALTER TABLE user_roles 
ADD CONSTRAINT "FKh8ciramu9cc9q3qcqiv4ue8a6"
FOREIGN KEY (role_id) REFERENCES roles (id);
-- rollback ALTER TABLE user_roles DROP CONSTRAINT "FKh8ciramu9cc9q3qcqiv4ue8a6";

-- changeset lakshman:1771450463197-7
ALTER TABLE user_roles 
ADD CONSTRAINT "FKhfh9dx7w3ubf1co1vdev94g3f"
FOREIGN KEY (user_id) REFERENCES users (id);
-- rollback ALTER TABLE user_roles DROP CONSTRAINT "FKhfh9dx7w3ubf1co1vdev94g3f";