-- liquibase formatted sql
-- changeset lakshman:1771792540826-1
CREATE TABLE
    permissions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        description VARCHAR(255),
        name VARCHAR(255) NOT NULL,
        CONSTRAINT "permissionsPK" PRIMARY KEY (id)
    );

-- changeset lakshman:1771792540826-2
CREATE TABLE
    role_permissions (
        role_id BIGINT NOT NULL,
        permission_id BIGINT NOT NULL,
        CONSTRAINT "role_permissionsPK" PRIMARY KEY (role_id, permission_id)
    );

-- changeset lakshman:1771792540826-3
CREATE TABLE
    user_permissions (
        user_id BIGINT NOT NULL,
        permission_id BIGINT NOT NULL,
        CONSTRAINT "user_permissionsPK" PRIMARY KEY (user_id, permission_id)
    );

-- changeset lakshman:1771792540826-4
ALTER TABLE users ADD "randomName" VARCHAR(255);

-- changeset lakshman:1771792540826-5
ALTER TABLE permissions ADD CONSTRAINT UC_PERMISSIONSNAME_COL UNIQUE (name);

-- changeset lakshman:1771792540826-6
ALTER TABLE role_permissions ADD CONSTRAINT "FKegdk29eiy7mdtefy5c7eirr6e" FOREIGN KEY (permission_id) REFERENCES permissions (id);

-- changeset lakshman:1771792540826-7
ALTER TABLE user_permissions ADD CONSTRAINT "FKkowxl8b2bngrxd1gafh13005u" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset lakshman:1771792540826-8
ALTER TABLE role_permissions ADD CONSTRAINT "FKn5fotdgk8d1xvo8nav9uv3muc" FOREIGN KEY (role_id) REFERENCES roles (id);

-- changeset lakshman:1771792540826-9
ALTER TABLE user_permissions ADD CONSTRAINT "FKq4qlrabt4s0etm9tfkoqfuib1" FOREIGN KEY (permission_id) REFERENCES permissions (id);