-- liquibase formatted sql
-- changeset lakshman:1773344041088-1
CREATE TABLE
    categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
        created_by BIGINT,
        is_active BOOLEAN NOT NULL,
        is_deleted BOOLEAN NOT NULL,
        updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
        updated_by BIGINT,
        description VARCHAR(255),
        image VARCHAR(255),
        name VARCHAR(255) NOT NULL,
        CONSTRAINT "categoriesPK" PRIMARY KEY (id)
    );

-- changeset lakshman:1773344041088-2
CREATE TABLE
    todo_categories (
        todo_id BIGINT NOT NULL,
        category_id BIGINT NOT NULL,
        CONSTRAINT "todo_categoriesPK" PRIMARY KEY (todo_id, category_id)
    );

-- changeset lakshman:1773344041088-3
CREATE TABLE
    todos (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
        created_by BIGINT,
        is_active BOOLEAN NOT NULL,
        is_deleted BOOLEAN NOT NULL,
        updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
        updated_by BIGINT,
        description VARCHAR(255),
        status VARCHAR(255),
        title VARCHAR(255) NOT NULL,
        user_id BIGINT NOT NULL,
        CONSTRAINT "todosPK" PRIMARY KEY (id)
    );

-- changeset lakshman:1773344041088-4
ALTER TABLE categories ADD CONSTRAINT UC_CATEGORIESNAME_COL UNIQUE (name);

-- changeset lakshman:1773344041088-5
ALTER TABLE todo_categories ADD CONSTRAINT "FK70ebg7mus2rrx4l0psy5pp5qk" FOREIGN KEY (todo_id) REFERENCES todos (id);

-- changeset lakshman:1773344041088-6
ALTER TABLE todos ADD CONSTRAINT "FK9605g76a1dggbvs18f2r80gvu" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset lakshman:1773344041088-7
ALTER TABLE todo_categories ADD CONSTRAINT "FKimif9rwjommw97qpqfd2jpkmt" FOREIGN KEY (category_id) REFERENCES categories (id);